### ISSUE TITLE
The 'RWSOLS_COMPUTER_NAME' variable does not support spaces on its values

### ISSUE THREAD

**Issue by SmartPhoneLover** [ex0nuss/Remote-Wake-Sleep-On-LAN-Docker#6]
**DESCRIPTION**
When I add a device name that contains spaces on its name, the container web interface fails to start when the container starts.
For example: if a a device name, like "My Server", not web interface is shown (blank); but, if I add it like "My-Server" or "MyServer" the web interface loads as expected.

**EXPECTED**
The web interface should be shown, as normally.

**Comment by ex0nuss** [comment]
Hi, 
thank you for opening up this issue and informing me about this bug.

The space gets piped correctly into the container, but the entrypoint-script formats it's wrong. The entrypoint-script creates the entire config-files and starts apache2 afterwards. It uses an sed-command. 

Unfortunately I don't have the time to look into this deeper right know. Please use an hyphen oder underscore for now. I add this information into the README too ;)

**Comment by SmartPhoneLover** [comment]
Ok, no problem. Thank you for replying ;)
